events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		listen 443 ssl;
		listen [::]:443 ssl;
		
		server_name server_name_here;
		
		ssl_certificate /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;
		ssl_protocols TLSv1.3 TLSv1.2;


    	location / {
       		try_files $uri $uri/ /index.php?$args;
	    	root /var/www/html;
    		index index.php index.html;
			location ~ \.php$ {
        		fastcgi_pass wordpress:9000;
        		include fastcgi_params;
        		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			}
		}

	    location ^~ /static/ {
    	    proxy_pass http://static:8080/;
    	}

    	location ^~ /adminer/ {
        	root /var/www;
    	    index adminer.php;
			location ~ \.php$ {
	    	    fastcgi_pass adminer:9000;
    	    	include fastcgi_params;
         	   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			}
		}

		location ^~ /portainer/ {
   			proxy_pass http://portainer:9000/;
    		proxy_http_version 1.1;
    		proxy_set_header Upgrade $http_upgrade;
    		proxy_set_header Connection 'upgrade';
    		proxy_set_header Host $host;
    		proxy_cache_bypass $http_upgrade;
			proxy_set_header X-Forwarded-Proto https;
		}
	}
}
